### PR TITLE
Set ethernet MAC and DDR voltage

### PR DESCRIPTION
**Pull request by chrisruk**

### CODE REVIEW

**Comment by chrisruk** [comment]
@floion just wondering if you'd be able to make this workflow re-run and approve? Many thanks

**Comment by floion** [comment]
@resin-jenkins ok to test

**Comment by chrisruk** [comment]
Just rebased an force pushed again, as noticed a new commit in master.  Not sure why the github action is failing though?

**Comment by floion** [comment]
Hi @chrisruk it looks like it's still not up to date with master? Can you rebase it again against master?

**Comment by chrisruk** [comment]
Sure, just rebased

**Review by floion — APPROVED** [review]

**Pull request merged**
