### PR TITLE
Determine correct DTB automatically and power on wifi adapter, in U-Boot

### PR DESCRIPTION
**Pull request by chrisruk**
Probe I2C display controllers, to determine which DTB to load. Alternatively use DTB from 'custom_fdt_file' variable, if specified and power on wifi adapter

Changelog-entry: Determine correct DTB automatically

### CODE REVIEW

**Review by floion — DISMISSED** [review]

**Review by floion — APPROVED** [review]

**Comment by floion** [comment]
Hi, can you rebase the PR please?

**Comment by chrisruk** [comment]
Just rebased it, thanks.

**Review by floion — APPROVED** [review]

**Comment by chrisruk** [comment]
Just rebased again, to get branch up to date

**Review by floion — APPROVED** [review]

**Comment by floion** [comment]
@resin-jenkins add to whitelist

**Pull request merged**
